apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: registry.cn-hangzhou.aliyuncs.com/zykj-test/test:v1
          ports:
          - name: http
            containerPort: 8080     --容器端口
            hostPort: 8081     --暴露端口
            protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    svc: web
spec:
  selector:
    app: web
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  type: ClusterIP
